name: Actions Runner Controller Demo
on:
  push:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    container:
      image: ghcr.io/linux-riscv/pw-builder:latest
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: lsb_release -a
    - run: cat /etc/apt/sources.list.d/debian.sources
    - run: cat /proc/cpuinfo
    - run: cat /proc/meminfo
    - run: sleep 10
