name: Actions Runner Controller Demo
on:
  push:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    container:
      image: ghcr.io/linux-riscv/pw-runner-multi:latest
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: pwd
    - run: df -h
    - name: Configure git
      run: |
        git config --global --add safe.directory '*'
    - name: Checkout git
      uses: actions/checkout@v4
    - run: lscpu
    - run: cat /proc/cpuinfo
    - run: cat /proc/meminfo
    - run: sleep 10
