name: Actions Runner Controller Demo

defaults:
  run:
    shell: bash -leo pipefail {0}

on:
  pull_request:

jobs:
  Explore-GitHub-Actions:
    if:  ${{ !endsWith(github.head_ref, '_test') }}
      # You need to use the INSTALLATION_NAME from the previous step
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref }}
      - run: echo "🎉 This job uses runner scale set runners!"
      - run: pwd
      - run: df -h
